<a href="https://colab.research.google.com/github/Kimheekyo35/Airforce_academy_chatbot/blob/main/california_analyst.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install kagglehub

Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (0.3.13)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub) (4.67.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2025.10.5)

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/adult-census-income")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'adult-census-income' dataset.
Path to dataset files: /kaggle/input/adult-census-income

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [9]:
df = pd.read_csv("../content/sample_data/california_housing_train.csv")

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [11]:
# 둘러보기
df.describe()

          longitude      latitude  ...  median_income  median_house_value
count  17000.000000  17000.000000  ...   17000.000000        17000.000000
mean    -119.562108     35.625225  ...       3.883578       207300.912353
std        2.005166      2.137340  ...       1.908157       115983.764387
min     -124.350000     32.540000  ...       0.499900        14999.000000
25%     -121.790000     33.930000  ...       2.566375       119400.000000
50%     -118.490000     34.250000  ...       3.544600       180400.000000
75%     -118.000000     37.720000  ...       4.767000       265000.000000
max     -114.310000     41.950000  ...      15.000100       500001.000000

[8 rows x 9 columns]

In [12]:
# null 값 확인
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [16]:
# row 개수, col 개수 알 수 있음
df.shape

(17000, 9)

In [17]:
# dataframe의 columns 아는 방법
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [19]:
# 해당 열의 data type 아는 방법
print(df['longitude'].dtype)

float64

In [20]:
def check_missing_col(dataframe):
  missing_col = []
  for col in dataframe.columns:
    missing_values = sum(dataframe[col].isna())
    is_missing = True if missing_values >= 1 else False
    # 만약 결측값이 있다면,
    if is_missing:
      print(f"결측치가 있는 컬럼은 {col} 입니다.")
      print(f'해당 컬럼에 총 {missing_values} 개의 결측치가 존재합니다.')
      missing_col.append(dataframe[col].dtype)
  if missing_col == []:
    print("결측치가 존재하지 않습니다.")
  return
  missing_col

print(check_missing_col(df))

결측치가 존재하지 않습니다.
[]

### unique()

- 특정 열 또는 시리즈에서 중복된 값 모두 제거하고, 고유한 값들만 뽑아서 보여주는 기능

In [21]:
print(df['longitude'].unique())

[-114.31 -114.47 -114.56 -114.57 -114.58 -114.59 -114.6  -114.61 -114.63
 -114.65 -114.66 -114.67 -114.68 -114.73 -114.94 -114.98 -115.22 -115.32
 -115.37 -115.38 -115.39 -115.4  -115.41 -115.46 -115.48 -115.49 -115.5
 -115.51 -115.52 -115.53 -115.54 -115.55 -115.56 -115.57 -115.58 -115.59
 -115.6  -115.62 -115.64 -115.69 -115.72 -115.73 -115.8  -115.84 -115.85
 -115.88 -115.9  -115.91 -115.93 -115.94 -115.95 -115.96 -115.98 -115.99
 -116.   -116.01 -116.02 -116.05 -116.06 -116.08 -116.09 -116.11 -116.12
 -116.14 -116.15 -116.16 -116.17 -116.18 -116.19 -116.2  -116.21 -116.22
 -116.23 -116.24 -116.25 -116.26 -116.27 -116.29 -116.3  -116.31 -116.32
 -116.33 -116.34 -116.35 -116.36 -116.37 -116.38 -116.39 -116.4  -116.41
 -116.42 -116.43 -116.44 -116.45 -116.46 -116.47 -116.48 -116.49 -116.5
 -116.51 -116.52 -116.53 -116.54 -116.55 -116.56 -116.57 -116.58 -116.6
 -116.61 -116.62 -116.66 -116.67 -116.68 -116.71 -116.72 -116.74 -116.75
 -116.76 -116.77 -116.78 -116.79 -116.8  -116.82 -116.83 -116.84 -116.85
 -116.86 -116.87 -116.88 -116.89 -116.9  -116.91 -116.92 -116.93 -116.94
 -116.95 -116.96 -116.97 -116.98 -116.99 -117.   -117.01 -117.02 -117.03
 -117.04 -117.05 -117.06 -117.07 -117.08 -117.09 -117.1  -117.11 -117.12
 -117.13 -117.14 -117.15 -117.16 -117.17 -117.18 -117.19 -117.2  -117.21
 -117.22 -117.23 -117.24 -117.25 -117.26 -117.27 -117.28 -117.29 -117.3
 -117.31 -117.32 -117.33 -117.34 -117.35 -117.36 -117.37 -117.38 -117.39
 -117.4  -117.41 -117.42 -117.43 -117.44 -117.45 -117.46 -117.47 -117.48
 -117.49 -117.5  -117.51 -117.52 -117.53 -117.54 -117.55 -117.56 -117.57
 -117.58 -117.59 -117.6  -117.61 -117.62 -117.63 -117.64 -117.65 -117.66
 -117.67 -117.68 -117.69 -117.7  -117.71 -117.72 -117.73 -117.74 -117.75
 -117.76 -117.77 -117.78 -117.79 -117.8  -117.81 -117.82 -117.83 -117.84
 -117.85 -117.86 -117.87 -117.88 -117.89 -117.9  -117.91 -117.92 -117.93
 -117.94 -117.95 -117.96 -117.97 -117.98 -117.99 -118.   -118.01 -118.02
 -118.03 -118.04 -118.05 -118.06 -118.07 -118.08 -118.09 -118.1  -118.11
 -118.12 -118.13 -118.14 -118.15 -118.16 -118.17 -118.18 -118.19 -118.2
 -118.21 -118.22 -118.23 -118.24 -118.25 -118.26 -118.27 -118.28 -118.29
 -118.3  -118.31 -118.32 -118.33 -118.34 -118.35 -118.36 -118.37 -118.38
 -118.39 -118.4  -118.41 -118.42 -118.43 -118.44 -118.45 -118.46 -118.47
 -118.48 -118.49 -118.5  -118.51 -118.52 -118.53 -118.54 -118.55 -118.56
 -118.57 -118.58 -118.59 -118.6  -118.61 -118.62 -118.63 -118.64 -118.65
 -118.66 -118.67 -118.68 -118.69 -118.7  -118.71 -118.72 -118.73 -118.74
 -118.75 -118.76 -118.77 -118.78 -118.79 -118.8  -118.81 -118.82 -118.83
 -118.84 -118.85 -118.86 -118.87 -118.88 -118.89 -118.9  -118.91 -118.92
 -118.93 -118.94 -118.95 -118.96 -118.97 -118.98 -118.99 -119.   -119.01
 -119.02 -119.03 -119.04 -119.05 -119.06 -119.07 -119.08 -119.09 -119.1
 -119.11 -119.12 -119.13 -119.14 -119.15 -119.16 -119.17 -119.18 -119.19
 -119.2  -119.21 -119.22 -119.23 -119.24 -119.25 -119.26 -119.27 -119.28
 -119.29 -119.3  -119.31 -119.32 -119.33 -119.34 -119.35 -119.36 -119.37
 -119.38 -119.39 -119.4  -119.41 -119.42 -119.43 -119.44 -119.45 -119.46
 -119.47 -119.48 -119.49 -119.5  -119.51 -119.52 -119.53 -119.54 -119.55
 -119.56 -119.57 -119.58 -119.59 -119.6  -119.61 -119.62 -119.63 -119.64
 -119.65 -119.66 -119.67 -119.68 -119.69 -119.7  -119.71 -119.72 -119.73
 -119.74 -119.75 -119.76 -119.77 -119.78 -119.79 -119.8  -119.81 -119.82
 -119.83 -119.84 -119.85 -119.86 -119.87 -119.88 -119.89 -119.9  -119.91
 -119.92 -119.93 -119.94 -119.95 -119.96 -119.97 -119.98 -119.99 -120.
 -120.01 -120.02 -120.03 -120.04 -120.05 -120.06 -120.07 -120.08 -120.09
 -120.1  -120.11 -120.12 -120.13 -120.14 -120.15 -120.16 -120.17 -120.18
 -120.19 -120.2  -120.21 -120.22 -120.23 -120.24 -120.25 -120.26 -120.27
 -120.28 -120.29 -120.3  -120.31 -120.32 -120.33 -120.34 -120.35 -120.36
 -120.37 -120.38 -120.39 -120.4  -120.41 -120.42 -120.43 -120.44 -120.45
 -120.46 -120.47 -120.48 -120.49 -120.5  -120.51 -120.52 -120.53 -120.54
 -120.55 -120.56 -120.57 -120.58 -120.59 -120.6  -120.61 -120.62 -120.63
 -120.64 -120.65 -120.66 -120.67 -120.68 -120.69 -120.7  -120.71 -120.72
 -120.73 -120.74 -120.75 -120.76 -120.77 -120.78 -120.79 -120.8  -120.81
 -120.82 -120.83 -120.84 -120.85 -120.86 -120.87 -120.88 -120.89 -120.9
 -120.91 -120.92 -120.93 -120.94 -120.95 -120.96 -120.97 -120.98 -120.99
 -121.   -121.01 -121.02 -121.03 -121.04 -121.05 -121.06 -121.07 -121.08
 -121.09 -121.1  -121.11 -121.12 -121.13 -121.14 -121.15 -121.16 -121.17
 -121.18 -121.19 -121.2  -121.21 -121.22 -121.23 -121.24 -121.25 -121.26
 -121.27 -121.28 -121.29 -121.3  -121.31 -121.32 -121.33 -121.34 -121.35
 -121.36 -121.37 -121.38 -121.39 -121.4  -121.41 -121.42 -121.43 -121.44
 -121.45 -121.46 -121.47 -121.48 -121.49 -121.5  -121.51 -121.52 -121.53
 -121.54 -121.55 -121.56 -121.57 -121.58 -121.59 -121.6  -121.61 -121.62
 -121.63 -121.64 -121.65 -121.66 -121.67 -121.68 -121.69 -121.7  -121.71
 -121.72 -121.73 -121.74 -121.75 -121.76 -121.77 -121.78 -121.79 -121.8
 -121.81 -121.82 -121.83 -121.84 -121.85 -121.86 -121.87 -121.88 -121.89
 -121.9  -121.91 -121.92 -121.93 -121.94 -121.95 -121.96 -121.97 -121.98
 -121.99 -122.   -122.01 -122.02 -122.03 -122.04 -122.05 -122.06 -122.07
 -122.08 -122.09 -122.1  -122.11 -122.12 -122.13 -122.14 -122.15 -122.16
 -122.17 -122.18 -122.19 -122.2  -122.21 -122.22 -122.23 -122.24 -122.25
 -122.26 -122.27 -122.28 -122.29 -122.3  -122.31 -122.32 -122.33 -122.34
 -122.35 -122.36 -122.37 -122.38 -122.39 -122.4  -122.41 -122.42 -122.43
 -122.44 -122.45 -122.46 -122.47 -122.48 -122.49 -122.5  -122.51 -122.52
 -122.53 -122.54 -122.55 -122.56 -122.57 -122.58 -122.59 -122.6  -122.61
 -122.62 -122.63 -122.64 -122.65 -122.66 -122.67 -122.68 -122.69 -122.7
 -122.71 -122.72 -122.73 -122.74 -122.75 -122.76 -122.77 -122.78 -122.79
 -122.8  -122.81 -122.82 -122.83 -122.84 -122.85 -122.86 -122.87 -122.88
 -122.89 -122.9  -122.91 -122.92 -122.93 -122.94 -122.95 -122.96 -122.97
 -122.98 -122.99 -123.   -123.01 -123.02 -123.03 -123.04 -123.07 -123.08
 -123.1  -123.11 -123.12 -123.13 -123.15 -123.16 -123.17 -123.18 -123.19
 -123.2  -123.21 -123.22 -123.23 -123.24 -123.25 -123.26 -123.32 -123.34
 -123.35 -123.36 -123.37 -123.38 -123.4  -123.41 -123.43 -123.48 -123.49
 -123.53 -123.54 -123.58 -123.59 -123.63 -123.64 -123.66 -123.68 -123.69
 -123.7  -123.71 -123.72 -123.73 -123.75 -123.76 -123.78 -123.79 -123.8
 -123.81 -123.82 -123.83 -123.84 -123.85 -123.88 -123.91 -123.96 -123.98
 -124.   -124.01 -124.02 -124.03 -124.05 -124.06 -124.07 -124.08 -124.09
 -124.1  -124.11 -124.13 -124.14 -124.15 -124.16 -124.17 -124.18 -124.19
 -124.21 -124.22 -124.23 -124.25 -124.26 -124.27 -124.3  -124.35]

In [23]:
df[['longitude','total_rooms']]

       longitude  total_rooms
0        -114.31       5612.0
1        -114.47       7650.0
2        -114.56        720.0
3        -114.57       1501.0
4        -114.57       1454.0
...          ...          ...
16995    -124.26       2217.0
16996    -124.27       2349.0
16997    -124.30       2677.0
16998    -124.30       2672.0
16999    -124.35       1820.0

[17000 rows x 2 columns]

In [26]:
df.loc[[0,1],['longitude','total_rooms']]

   longitude  total_rooms
0    -114.31       5612.0
1    -114.47       7650.0

In [27]:
df.iloc[[0,1]]

   longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0

[2 rows x 9 columns]

In [29]:
#0이랑 3만 뽑음
df.iloc[[0,3]]

   longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
3    -114.57     33.64  ...         3.1917             73400.0

[2 rows x 9 columns]

In [31]:
# 0부터 2까지의 행을 모두 뽑음
df.iloc[0:3]

   longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0

[3 rows x 9 columns]

### iloc[x,y] - integer location

- 특정한 행과 열 찾고싶으면 이렇게 하면 됨

### loc[x,y] - location (이름 Label기반)

In [34]:
# 0번째 행, 3번째 열 찾고싶을 때

df.iloc[0,3]

np.float64(5612.0)

In [35]:
df.loc[0,'total_rooms']

np.float64(5612.0)